[project]
name = "connect-strava-sync"
version = "0.1.0"
description = "A CLI application to push Garmin Connect names and descriptions to Strava."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "datetime>=5.5",
    "garminconnect>=0.2.30",
    "garth>=0.5.17",
    "python-dotenv>=1.1.1",
    "pyyaml>=6.0.2",
    "stravalib>=2.4",
    "typing>=3.10.0.0",
]
